[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[workspace]
members = ["programs/*"]

[programs.localnet]
zombie_arena_protocol = "ZAPxxx111111111111111111111111111111111111"

[programs.devnet]
zombie_arena_protocol = "ZAPxxx111111111111111111111111111111111111"

[programs.mainnet]
zombie_arena_protocol = "ZAPxxx111111111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"